# Generated by Django 6.1 on 2026-08-30 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date_admitted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='exam',
            name='date_picked_up',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='taken_by',
            field=models.CharField(default='Kate', max_length=30),
        ),
        migrations.AddField(
            model_name='exam',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exam',
            name='vet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='litter',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='preventative',
            name='brand',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='preventative',
            name='date_given',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='preventative',
            name='dosage',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='preventative',
            name='next_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preventative',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='test',
            name='date_administered',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='test',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='dosage',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='issue',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='treatment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='date_given',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='next_due',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='weight',
            name='time',
            field=models.CharField(blank=True, choices=[('am', 'am'), ('pm', 'pm')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('lb', 'lb')], default='lb', max_length=30),
        ),
        migrations.AddField(
            model_name='weight',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
