# Generated by Django 6.1 on 2026-08-30 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litter', '0002_exam_date_admitted_exam_date_picked_up_exam_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='litter.cat'),
        ),
        migrations.AddField(
            model_name='litter',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preventative',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='litter.cat'),
        ),
        migrations.AddField(
            model_name='test',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='litter.cat'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='litter.cat'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='litter.cat'),
        ),
        migrations.AddField(
            model_name='weight',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='litter.cat'),
        ),
    ]
