# Generated by Django 6.1 on 2026-09-02 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litter', '0003_cat_is_deleted_exam_cat_litter_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medications', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='litter.cat')),
            ],
        ),
    ]
